export const ISSUE_REQUEST="ISSUE_REQUEST"; 
export const ISSUE_DATA_SUCCESS = "ISSUE_DATA_SUCCESS";
export const ISSUE_DATA_FAILURE = "ISSUE_DATA_FAILURE";
export const ISSUE_RESET = "ISSUE_RESET";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const INCREMENT_WATCH_COUNTER="INCREMENT_WATCH_COUNTER";
export const INCREMENT_STAR_COUNTER="INCREMENT_STAR_COUNTER";
export const INCREMENT_FORK_COUNTER="INCREMENT_FORK_COUNTER";